/*
 * Name: Brainfuck Compiler C
 * Author: Max Base
 * Date: 2022/09/29
 * Repository: https://github.com/basemax/BrainfuckCompilerC
 */

#include <stdio.h>
#include <stdlib.h>

char* read_from_cli() {
    char* program = malloc(10000 * sizeof(char));

    int i = 0;
    while((program[i++] = getchar()) != 'x');

    program[i-1] = '\0';

    return program;
}

char* read_from_file(char* filepath) {
	FILE* file = fopen(filepath, "rb");
	if (file == NULL) {
		printf("Error: Could not open file \"%s\".", filepath);
		exit(74);
	}

	fseek(file, 0L, SEEK_END);
	size_t fileSize = ftell(file);
	rewind(file);

	char* program = (char*)malloc(fileSize + 1);
	if (program == NULL) {
		printf("Error: Not enough memory to read \"%s\".", filepath);
		exit(74);
	}

	size_t bytesRead = fread(program, sizeof(char), fileSize, file);
	if (bytesRead < fileSize) {
		printf("Error: Could not read the \"%s\".", filepath);
		exit(74);
	}

	program[bytesRead] = '\0';

	fclose(file);
	return program;
}

void run(char* program, FILE* outfile) {
    // | >	| Move the pointer to the right |
    // | <	| Move the pointer to the left |
    // | +	| Increment the memory cell at the pointer |
    // | -	| Decrement the memory cell at the pointer |
    // | .	| Output the character signified by the cell at the pointer |
    // | ,	| Input a character and store it in the cell at the pointer |
    // | [	| Jump past the matching ] if the cell at the pointer is 0 |
    // | ]	| Jump back to the matching [ if the cell at the pointer is nonzero |
    // | any | All characters other than ><+-.,[] should be considered comments and ignored |

    fprintf(outfile, "/*\n * This source was automatically generated by Brainfuck Compiler C\n */\n");
    fprintf(outfile, "#include <stdio.h>\n");
    fprintf(outfile, "#include <stdlib.h>\n\n");
    fprintf(outfile, "int main() {\n");

    // fprintf(outfile, "\tchar *memory = (char*) malloc(30000 * sizeof(char));\n");
    fprintf(outfile, "\tchar buffer[30000];\n");
    fprintf(outfile, "\tchar* memory = buffer;\n");
    	
    while(*program != EOF){
        switch(*program){
            case '>': fprintf(outfile, "\tmemory++;\n"); break;
            case '<': fprintf(outfile, "\tmemory--;\n"); break;
            case '+': fprintf(outfile, "\t++*memory;\n"); break;
            case '-': fprintf(outfile, "\t--*memory;\n"); break;
            case '[': fprintf(outfile, "\twhile(*memory){\n"); break;
            case ']': fprintf(outfile, "\t}\n"); break;
            case '.': fprintf(outfile, "\tputchar(*memory);\n"); break;
            case ',': fprintf(outfile, "\t*memory=getchar();\n"); break;
        }
        *program++;
    }
    fprintf(outfile,"\texit(0);\n\treturn 0;\n}\n");
}

int main(int argc, char** argv) {
    char* program = NULL;

    if (argc > 2) {
        printf("Error: ./%s [file.bf]\n", argv[0]);
        return 1;
    } else if (argc == 1) {
        program = read_from_cli();
    } else {
        program = read_from_file(argv[1]);
    }

    if (program != NULL) {
        // printf("%s\n===========\n", program);
        run(program, stdout);
        free(program);
    }

    return 0;
}
